/* Generated by Cython 0.25.1 */

#ifndef __PYX_HAVE__fib_cdef_module
#define __PYX_HAVE__fib_cdef_module


#ifndef __PYX_HAVE_API__fib_cdef_module

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *fib(PyObject *);

#endif /* !__PYX_HAVE_API__fib_cdef_module */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initfib_cdef_module(void);
#else
PyMODINIT_FUNC PyInit_fib_cdef_module(void);
#endif

#endif /* !__PYX_HAVE__fib_cdef_module */
